general:
  name: HPO Taunt pack
  description: Taunts carefully selected by the HPO group.

taunts:
  - name: Nice
    regex: (?i)n(o)?ice
    path: audio/nice.wav
  - name: Huh
    regex: (?i)\bhu+h+\b
    path: audio/huh.wav
  - name: What's Heavier
    regex: (?i)what(s| is|'s) heavier
    path: audio/whats_heavier.wav
  - name: Wow
    regex: (?i)w(o+|au)w
    path: audio/wow.wav